# Ingress cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    protocol: TCP
  - containerPort: 443
    protocol: TCP
- role: worker
- role: worker
- role: worker