apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-vault-secret
  labels:
    app.kubernetes.io/version: "1.0.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: search
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
    vault.hashicorp.com/agent-inject-template-app-config: |
      {{ with secret "dev/data/go-app" -}}
        export BANNER="{{ .Data.data.BANNER }}"
      {{- end }}
    vault.hashicorp.com/service: "http://kind-vault.vault.svc:8200"
    # vault.hashicorp.com/tls-skip-verify: 'true'
    vault.hashicorp.com/role: "go-app"
    vault.hashicorp.com/agent-inject-secret-app-config: "dev/data/go-app"
    vault.hashicorp.com/agent-pre-populate-only: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/auth-path: "auth/kubernetes/kind_cluster"
    vault.hashicorp.com/agent-run-as-same-user: "true"
    vault.hashicorp.com/agent-inject-perms-app-config: "0770"
spec:
  description: >-
    This task print the secret injected by vault init container. The init container will get injected by vault agent.
  params:
    - name: image
      description: sample image
      type: string
      default: "diquzart/go-app"
  steps:
    - name: echo
      image: "$(params.image)"
      command: ["/bin/sh"]
      args:
        [
          "-c",
          "source /vault/secrets/app-config && env > /vault/secrets/test && cat /vault/secrets/test",
        ]
      securityContext:
        runAsUser: 100
